#' Display summary from a model generated by rms
#' @param s a model returned by rms
#' @param width the width of the table in pixels
#' @export
display_rms_summary <- function(m,width=150)
{
  if (!("rms" %in% class(m)))
  {
    stop("Can only display a summary from an rms model object")
  }
  w <- paste0("width: ",width,"px")
  s <- summary(m)
  rn <- rownames(s)
  s <- as.data.frame(s)
  rn_remove <- grep("Odds Ratio|Hazard Ratio", rn)
  if (length(rn_remove) > 0) 
  {
    rn_keep <- rn[-rn_remove]
  } else {
    rn_keep <- rn
  }
  con_table <- NULL
  for (i in rn)
  {
    if (any(which(i == rn) %in% rn_remove))
    {
      temp <- data.frame(Factor = i, p = NA)
      con_table <- rbind(con_table,temp)
    } else {
      if (grepl("-",i)){
        vals <- strsplit(i," - |:")[[1]]
        coeff <- vals[1]
        low <- vals[2]
        high <- vals[3]
      } else {
        coeff <- i
        low <- s[i,"Low"]
        high <- s[i,"High"]
      }
      a <- list(low)
      names(a) <- coeff
      b <- list(high)
      names(b) <- coeff
      temp <- contrast(m,a,b)
      temp <- data.frame(Factor=i,p=temp$Pvalue)
      con_table <- rbind(con_table,temp)
    }
  }
  
  s <- cbind(s,con_table)
  s <- s[,c(9,1:8,10)]
  rownames(s) <- NULL
  s[,2:8] <- apply(s[,2:8],2,round,2)
  s$p <- formatC(s$p, format = "e", digits = 3)
  display_df(s,width=width)
}
